### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sameerkali**
I make changes in the readme.md file take my time and make it precise and beautiful please check it and approve it, it makes your project better, thanks & regards @sameerkali

```diff
-old readme.md
+new and better one
```
# Thankyou

### CODE REVIEW

**Review by saranstack — APPROVED** [review]

**Comment by saranstack** [comment]
Updated Readme file by Sameer faridi

**Review by saranstack — COMMENTED** [review]
# Thank you

**Review by sameerkali — COMMENTED** [review]
do it again

**Review by saranstack — COMMENTED** [review]
asdfghjkl;

**Pull request merged**
